from PySide import QtCore, QtGui

class Ui_in_out_settings(object):
    def setupUi(self, in_out_settings):
        in_out_settings.setObjectName("in_out_settings")
        in_out_settings.resize(457, 492)
        self.gridLayout_2 = QtGui.QGridLayout(in_out_settings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        self.outputsLabel = QtGui.QLabel(in_out_settings)
        self.outputsLabel.setObjectName("outputsLabel")
        self.gridLayout_2.addWidget(self.outputsLabel, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.inputsLabel = QtGui.QLabel(in_out_settings)
        self.inputsLabel.setObjectName("inputsLabel")
        self.gridLayout_2.addWidget(self.inputsLabel, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtGui.QPushButton(in_out_settings)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.okButton = QtGui.QPushButton(in_out_settings)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 2, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outputView = QtGui.QTableView(in_out_settings)
        self.outputView.setObjectName("outputView")
        self.verticalLayout_3.addWidget(self.outputView)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outputAddButton = QtGui.QPushButton(in_out_settings)
        self.outputAddButton.setObjectName("outputAddButton")
        self.horizontalLayout_4.addWidget(self.outputAddButton)
        self.outputRemoveButton = QtGui.QPushButton(in_out_settings)
        self.outputRemoveButton.setObjectName("outputRemoveButton")
        self.horizontalLayout_4.addWidget(self.outputRemoveButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputView = QtGui.QTableView(in_out_settings)
        self.inputView.setObjectName("inputView")
        self.verticalLayout.addWidget(self.inputView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputAddButton = QtGui.QPushButton(in_out_settings)
        self.inputAddButton.setObjectName("inputAddButton")
        self.horizontalLayout_2.addWidget(self.inputAddButton)
        self.inputRemoveButton = QtGui.QPushButton(in_out_settings)
        self.inputRemoveButton.setObjectName("inputRemoveButton")
        self.horizontalLayout_2.addWidget(self.inputRemoveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(in_out_settings)
        QtCore.QMetaObject.connectSlotsByName(in_out_settings)

    def retranslateUi(self, in_out_settings):
        in_out_settings.setWindowTitle(QtGui.QApplication.translate("in_out_settings", "Edit Input/Output Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.outputsLabel.setText(QtGui.QApplication.translate("in_out_settings", "Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.inputsLabel.setText(QtGui.QApplication.translate("in_out_settings", "Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("in_out_settings", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("in_out_settings", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.outputAddButton.setText(QtGui.QApplication.translate("in_out_settings", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.outputRemoveButton.setText(QtGui.QApplication.translate("in_out_settings", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.inputAddButton.setText(QtGui.QApplication.translate("in_out_settings", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.inputRemoveButton.setText(QtGui.QApplication.translate("in_out_settings", "Remove", None, QtGui.QApplication.UnicodeUTF8))


